const toggle=document.querySelector('.nav-toggle'),nav=document.querySelector('.nav');
toggle?.addEventListener('click',()=>{const o=nav.classList.toggle('open');toggle.setAttribute('aria-expanded',o?'true':'false')});
document.querySelectorAll('.nav a').forEach(a=>a.addEventListener('click',()=>nav.classList.remove('open')));
const bar=document.querySelector('.scroll-progress span');
addEventListener('scroll',()=>{const m=document.documentElement.scrollHeight-innerHeight;bar.style.width=(m?scrollY/m*100:0)+'%'},{passive:true});
const obs=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');obs.unobserve(e.target)}}),{threshold:.12});
document.querySelectorAll('.section,.card,.photo,.zampogna,.reservation-card,.territory-copy').forEach(e=>{e.classList.add('reveal');obs.observe(e)});
const filters=document.querySelectorAll('.filter'),cats=document.querySelectorAll('.menu-category,.pizza-menu'),search=document.getElementById('menuSearch');
function filterMenu(){const a=document.querySelector('.filter.active')?.dataset.filter||'all',q=(search?.value||'').toLowerCase();cats.forEach(c=>{const ok=a==='all'||c.dataset.category===a;let found=ok;c.querySelectorAll('.item,.pizza-columns p').forEach(i=>{const m=!q||i.textContent.toLowerCase().includes(q);i.classList.toggle('match',!!q&&m);if(q&&ok&&m)found=true});c.classList.toggle('hidden',!found)})}
filters.forEach(b=>b.addEventListener('click',()=>{filters.forEach(x=>x.classList.remove('active'));b.classList.add('active');filterMenu()}));search?.addEventListener('input',filterMenu);
const gallery=[...document.querySelectorAll('.gallery-item')],lb=document.getElementById('lightbox'),img=document.getElementById('lightboxImage'),cap=document.getElementById('lightboxCaption');let current=0;
function openGallery(i){current=i;const x=gallery[i];img.src=x.dataset.full;img.alt=x.querySelector('img').alt;cap.textContent=x.querySelector('figcaption').textContent.replace('↗','').trim();lb.classList.add('open');lb.setAttribute('aria-hidden','false')}
function closeGallery(){lb.classList.remove('open');lb.setAttribute('aria-hidden','true')}function move(d){openGallery((current+d+gallery.length)%gallery.length)}
gallery.forEach((x,i)=>x.addEventListener('click',()=>openGallery(i)));document.querySelector('.lightbox-close')?.addEventListener('click',closeGallery);document.querySelector('.lightbox-prev')?.addEventListener('click',()=>move(-1));document.querySelector('.lightbox-next')?.addEventListener('click',()=>move(1));lb?.addEventListener('click',e=>{if(e.target===lb)closeGallery()});document.addEventListener('keydown',e=>{if(!lb?.classList.contains('open'))return;if(e.key==='Escape')closeGallery();if(e.key==='ArrowLeft')move(-1);if(e.key==='ArrowRight')move(1)});
const form=document.getElementById('reservationForm');form?.addEventListener('submit',e=>{e.preventDefault();const d=new FormData(form);const msg=`Buonasera, vorrei richiedere un tavolo presso Terra Nostra.\n\nNome: ${d.get('nome')}\nPersone: ${d.get('persone')}\nData: ${d.get('data')}\nOrario: ${d.get('orario')}\nNote: ${d.get('note')||'Nessuna'}`;const t=document.createElement('div');t.className='toast';t.textContent='Richiesta preparata. Ora puoi contattare il ristorante al 0865 954135.';document.body.appendChild(t);setTimeout(()=>t.remove(),5000);location.href='tel:+390865954135'});
const date=document.querySelector('#reservationForm input[type=date]');if(date){const d=new Date(Date.now()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,10);date.min=d}
document.getElementById('year').textContent=new Date().getFullYear();
